"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.QUEUE_TIMEOUT = exports.RESPONSE_TIMEOUT = exports.DEFAULT_RETRY_COUNT = exports.FUNCTION_CODES = void 0;
const FUNCTION_CODES = {
  READ_COILS: 1,
  READ_DISCRETE_INPUTS: 2,
  READ_HOLDING_REGISTERS: 3,
  READ_INPUT_REGISTERS: 4,
  WRITE_SINGLE_COIL: 5,
  WRITE_SINGLE_REGISTER: 6,
  WRITE_MULTIPLE_COILS: 15,
  WRITE_MULTIPLE_REGISTERS: 16
};
exports.FUNCTION_CODES = FUNCTION_CODES;
const DEFAULT_RETRY_COUNT = 10;
exports.DEFAULT_RETRY_COUNT = DEFAULT_RETRY_COUNT;
const RESPONSE_TIMEOUT = 500;
exports.RESPONSE_TIMEOUT = RESPONSE_TIMEOUT;
const QUEUE_TIMEOUT = 50;
exports.QUEUE_TIMEOUT = QUEUE_TIMEOUT;